parameters:
#    bruens_theming.example.class: Bruens\ThemingBundle\Example

services:
#    bruens_theming.example:
#        class: %bruens_theming.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
