<?php

namespace Bruens\FlexConnectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlexConnectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlexConnectRepository extends EntityRepository
{
}