parameters:
#    bruens_time_entry.example.class: Bruens\TimeEntryBundle\Example

services:
#    bruens_time_entry.example:
#        class: %bruens_time_entry.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
